ALTER SESSION SET "_ORACLE_SCRIPT"=true;
CREATE USER "PROYECTO_PROGRA" IDENTIFIED BY "123456";

GRANT "CONNECT" TO "PROYECTO_PROGRA";

GRANT CREATE TABLE TO "PROYECTO_PROGRA";

GRANT CREATE SEQUENCE TO "PROYECTO_PROGRA";

ALTER USER PROYECTO_PROGRA QUOTA UNLIMITED ON USERS;